### PR TITLE
Upgrade selectors

### PR DESCRIPTION
**Pull request by nallenscott**
Fixes deprecated selectors in Atom 1.13.0 and above.

### CODE REVIEW

**Comment by claudiodangelis** [comment]
Hi, thanks for this. I'm no longer maintaining this package, would you like to be the new maintainer?

**Comment by nallenscott** [comment]
That would be great, thank you!

**Comment by claudiodangelis** [comment]
I'm out of office, will be back later this week and will transfer the
ownership  of the project to you.

Thanks again for your contribution,
Claudio

Il dom 26 mag 2019, 15:08 Nathan Allen <notifications@github.com> ha
scritto:

**Comment by nallenscott** [comment]
Sounds good, thanks!

**Comment by claudiodangelis** [comment]
@nallenscott hi, I'm initiating the process of transfering the repository, please make sure to delete your fork otherwise I can't proceed.

I reached out  to Atom support to request information about transfering the package, will keep you updated on this. Thanks for maintaining this project :tada: !

More info: https://help.github.com/en/articles/transferring-a-repository

**Comment by nallenscott** [comment]
Deleted, and my pleasure. Thanks for the opportunity!

**Pull request merged**
